### ISSUE TITLE
Proposal to allow to override the NodeFS cache store folder.

### ISSUE THREAD

**Issue by nocodehummel** [gadicc/jest-fetch-mock-cache#5]
Allow to override the NodeFS cache folder and use Jest styled folder name as default.

```
constructor(location?: string) {
  super();
  this._location = location || "__cache__";
}
```

**Comment by gadicc** [comment]
Ah oops I commented all together in https://github.com/gadicc/jest-fetch-mock-cache/pull/4#issuecomment-2066166079 (see last point).
